# Generated by Django 4.2.4 on 2023-09-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('hasAiTrained', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
