# Generated by Django 4.2.4 on 2023-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='qty',
            new_name='_13_qty',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='name',
        ),
        migrations.AddField(
            model_name='workorder',
            name='_16A_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_18A_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_20_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_22_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_26_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_29_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_33_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_35_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_7A_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='_9_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
