# Generated by Django 4.2.4 on 2023-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_qty_workorder__13_qty_remove_workorder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
