# Generated by Django 4.2.4 on 2023-09-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_workorder_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
