# Generated by Django 4.2.4 on 2023-09-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_workorder_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='aiWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('worklist_id', models.PositiveIntegerField(default=1)),
                ('list_order', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
