# Generated by Django 4.2.4 on 2023-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_aiworkorder_training_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_code', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='qrcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
