# Generated by Django 4.2.4 on 2023-09-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aiTraining_state',
            field=models.CharField(choices=[('no_training', 'no_training'), ('is_training', 'is_training'), ('finish_training', 'finish_training')], default='no_training', max_length=180),
        ),
    ]
