# Generated by Django 4.2.4 on 2023-09-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_count_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_file_step2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
