# Generated by Django 4.2.4 on 2023-09-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_order_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aiTraining_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
