# Generated by Django 4.2.4 on 2023-09-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_order_aitraining_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcodeExecute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_execute', models.BooleanField(default=False)),
            ],
        ),
    ]
