# Generated by Django 4.2.4 on 2023-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_order_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
