# Generated by Django 4.2.4 on 2023-10-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_order_display'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRcodeExecute',
        ),
        migrations.RemoveField(
            model_name='order',
            name='display',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unique_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='upload_qrcode_select',
        ),
    ]
