# Generated by Django 4.2.4 on 2023-10-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_multipleorderitem_multiple_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleorder',
            old_name='order_list',
            new_name='orderId_list',
        ),
    ]
