# Generated by Django 4.2.4 on 2023-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_multipleorderitem_multiple_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('executing_index', models.PositiveIntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='multipleorderitem',
            name='multiple_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipleOrder', to='mainapp.multipleorder'),
        ),
    ]
