# Generated by Django 4.2.4 on 2023-11-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_executingorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutingOrder',
        ),
    ]
