# Generated by Django 4.2.4 on 2023-11-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_delete_executingorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('executing_index', models.PositiveIntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
