# Generated by Django 4.2.4 on 2023-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_executingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_today_latest',
            field=models.BooleanField(default=True),
        ),
    ]
