# Generated by Django 4.2.4 on 2023-11-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_order_is_today_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleorder',
            name='is_today_latest',
            field=models.BooleanField(default=True),
        ),
    ]
