# Generated by Django 4.2.4 on 2024-03-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_historyrecord_reset_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='reset_all_index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
