# Generated by Django 4.2.4 on 2024-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_historyrecord_reset_all_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
